services:
  hyperbeam:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/dtfiedler/hyperbeam:latest
    container_name: hyperbeam
    network_mode: host # note: not recommended for production
    restart: unless-stopped
    mem_limit: 8g
    mem_reservation: 8g
    memswap_limit: 8g
    ports:
      - "10000:10000"
    volumes:
      - ./wallets/wallet.json:/app/hyperbeam-key.json
      - ./config.flat:/app/config.flat


  cu:
    image: ghcr.io/permaweb/ao-cu:latest
    container_name: cu
    network_mode: host # note: not recommended for production
    volumes:
      - ${CU_WALLET_FILE:-./wallets/wallet.json}:/usr/app/wallet.json
    ports:
      - ${CU_PORT:-6363}:${CU_PORT:-6363}
    environment:
      PORT: ${CU_PORT:-6363}
      WALLET_FILE: ${CU_WALLET_FILE:-./wallet.json}
      NODE_CONFIG_ENV: ${NODE_CONFIG_ENV:-development}
      NODE_HEAPDUMP_OPTIONS: ${NODE_HEAPDUMP_OPTIONS:-nosignal}
      PROCESS_CHECKPOINT_TRUSTED_OWNERS: ${PROCESS_CHECKPOINT_TRUSTED_OWNERS:-fcoN_xJeisVsPXA-trzVAuIiqO3ydLQxM-L4XbrQKzY}
      GRAPHQL_URL: ${GRAPHQL_URL:-https://arweave-search.goldsky.com/graphql}
      CHECKPOINT_GRAPHQL_URL: ${CHECKPOINT_GRAPHQL_URL:-https://arweave-search.goldsky.com/graphql}
      DISABLE_PROCESS_CHECKPOINT_CREATION: ${DISABLE_PROCESS_CHECKPOINT_CREATION:-true}
      PROCESS_WASM_MEMORY_MAX_LIMIT: ${PROCESS_WASM_MEMORY_MAX_LIMIT:-17179869184}

